#lists []= ordered, changable and allows duplicates
wards = ['A', 'B', 'C','B']
#wards.append('D')# adds a single item to the end
#wards.extend(['E', 'F'])#adds multiple items to the end
#wards.insert(1, 'H')#inserts at a specific index in this case second
#wards.pop(1)# removes the second value. and default is last
#wards.remove('A')#removes a vcalue
#wards.clear()#removes all
#wards.index('D')#runs the value if not in the list it returns an error
#b_count = wards.count('B')#creates a b count to print
#print(b_count)
#wards.reverse()#reverses
wards.sort('A')
#and many mor

print(wards)

